name: My first workflow

on: 
  workflow_dispatch:

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout action
          uses: actions/checkout@v4
        - name: welcome message 
          run: echo "This is my fist github action job to run"
        - name: List files
          run: ls -ltr 
        - name: Execute shell script
          run: 
            chmod +x python.sh 
            ./python.sh
        - name: upload-python-file 
          uses: actions/upload-artifact@v4
          with:
           name: python-shell-script
           path: python.sh
    second_job:
        needs: [first_job]
        concurrency:
          group: production_workload
          cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
        - name: Download python.sh file
          uses: actions/download-artifact@v4
          with:
            name: python-shell-script
            
        - name: list all the file 
          run: cat python.sh
            sleep 300s
          
        
        
         
