name: My first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout action
          uses: actions/checkout@v4
        - name: welcome message 
          run: echo "This is my fist github action job to run"
        - name: List files
          run: | 
            ls -ltr 
            chmod +x
            ./python.sh
         
